Repository UniOfGreenwich/Team-GECCO, pull requests merged in 2025-04, with the labels that each got.

#32 feat(#20): Car Finance Calculation Implementation
  backend/BudgetingCalculator/build.gradle
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/controller/BudgetingController.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/BudgetingException.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/ErrorCode.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/GlobalExceptionHandler.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/BudgetingUserRequest.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingErrorResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserCarFinanceResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserMortgageResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingCarFinancePayment.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingMortgageDeposit.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/FieldValidation.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/util/FinanceUtil.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingCarFinancePaymentTest.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingMortgageDepositTest.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/util/FinanceUtilTest.java
  backend/Hoppscotch/backend-testing.json
Labels: enhancement

#33 CORs Capatibility
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/config/WebConfig.java
Labels: enhancement

#34 calculator creation + necessary changes
  frontend/BudgetingBuddy-frontend/src/App.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Calculator/calculator.tsx
  frontend/BudgetingBuddy-frontend/src/Components/DynamicForm/dynamicForm.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Registration-Form/RegistrationForm.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Stepper/stepper.scss
  frontend/BudgetingBuddy-frontend/src/Pages/GatherUserInforPage/userInformation.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/MortageCalculator/mortgageCalculatorPage.tsx
  frontend/BudgetingBuddy-frontend/src/store/UserMoneyInfoStore.tsx
  frontend/BudgetingBuddy-frontend/src/types/UserMoneyInfoContextTypes.ts
Labels: enhancement

#41 test configuration
  frontend/BudgetingBuddy-frontend/package-lock.json
  frontend/BudgetingBuddy-frontend/package.json
  frontend/BudgetingBuddy-frontend/vitest.config.js
Labels: enhancement

#43 fixed input fields not working
  frontend/BudgetingBuddy-frontend/src/Components/DynamicForm/dynamicForm.tsx
Labels: bug, documentation

#44 AboutUsTest
  frontend/BudgetingBuddy-frontend/src/Pages/AboutUsPage/AboutUs.test.tsx
Labels: test

#45 Feature/Ticket-backendDevelopment-HolidayImplmentation
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/controller/BudgetingController.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/ErrorCode.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/BudgetingUserRequest.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserHolidayResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingCarFinancePayment.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingHolidayAmount.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingMortgageDeposit.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/FieldValidation.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/util/FinanceUtil.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingCarFinancePaymentTest.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingHolidayAmountTest.java
  backend/Hoppscotch/backend-testing.json
Labels: enhancement

#46 Contact page test
  frontend/BudgetingBuddy-frontend/src/Pages/ContactPage/ContactPage.test.tsx
Labels: test

#48 Help page test
  frontend/BudgetingBuddy-frontend/src/Pages/HelpPage/HelpPage.test.tsx
Labels: test

#52 completed mortage page
  frontend/BudgetingBuddy-frontend/src/Components/Stepper/stepper.scss
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.scss
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.tsx
Labels: enhancement

#53 Privacy Page Test
  frontend/BudgetingBuddy-frontend/src/Pages/PrivacyPage/PrivacyPage.test.tsx
Labels: test

#55 Selection page test
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/SelectionPage.test.tsx
Labels: test

#54 linked up mortage to selection page
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/selection.tsx
Labels: enhancement

#57 Welcome page test
  frontend/BudgetingBuddy-frontend/src/Pages/WelcomePage/WelcomePage.test.tsx
Labels: test

#62 created car finance page
  frontend/BudgetingBuddy-frontend/src/App.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/CarFinance.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/CarFinancePage.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/car.scss
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/car.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/GatherUserInforPage/userInformation.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/selection.tsx
Labels: enhancement

#63 Feature(#29): Refactor Architecture Diagram
  SYSTEM-MODELLING.md
  finance-helper-frontend/src/assets/architecture-diagram-budgeting-app.png
Labels: documentation, duplicate

#66 styled the car finance calculator table
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/CarFinancePage.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/car.scss
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.scss
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.tsx
Labels: enhancement

#67 formamtted all the files using prettier
  frontend/BudgetingBuddy-frontend/README.md
  frontend/BudgetingBuddy-frontend/eslint.config.js
  frontend/BudgetingBuddy-frontend/package-lock.json
  frontend/BudgetingBuddy-frontend/package.json
  frontend/BudgetingBuddy-frontend/src/App.css
  frontend/BudgetingBuddy-frontend/src/App.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Calculator/calculator.scss
  frontend/BudgetingBuddy-frontend/src/Components/Calculator/calculator.tsx
  frontend/BudgetingBuddy-frontend/src/Components/DynamicForm/dynamicForm.scss
  frontend/BudgetingBuddy-frontend/src/Components/DynamicForm/dynamicForm.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Standard-input/standardInput.tsx
  frontend/BudgetingBuddy-frontend/src/Components/Stepper/stepper.scss
  frontend/BudgetingBuddy-frontend/src/Components/Stepper/stepper.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/AboutUsPage/AboutUs.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/AboutUsPage/aboutus.scss
  frontend/BudgetingBuddy-frontend/src/Pages/AboutUsPage/aboutus.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/CarFinancePage.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/CarFinancePage/car.scss
  frontend/BudgetingBuddy-frontend/src/Pages/ContactPage/ContactPage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/ContactPage/contact.scss
  frontend/BudgetingBuddy-frontend/src/Pages/ContactPage/contact.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/DashboardPage/dashboard.scss
  frontend/BudgetingBuddy-frontend/src/Pages/DashboardPage/dashboard.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/FinancialQuizPage/FinancialQuizPage.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/FinancialQuizPage/financialQuiz.scss
  frontend/BudgetingBuddy-frontend/src/Pages/GatherUserInforPage/userInformation.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/GatherUserInforPage/userinfo.scss
  frontend/BudgetingBuddy-frontend/src/Pages/HelpPage/HelpPage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/HelpPage/help.scss
  frontend/BudgetingBuddy-frontend/src/Pages/HelpPage/help.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.scss
  frontend/BudgetingBuddy-frontend/src/Pages/MortgageCalculator/mortgageCalculator.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/MortgagePage/MortagePage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/MortgagePage/mortgage.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/PrivacyPage/PrivacyPage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/PrivacyPage/privacy.scss
  frontend/BudgetingBuddy-frontend/src/Pages/PrivacyPage/privacy.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/SelectionPage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/selection.scss
  frontend/BudgetingBuddy-frontend/src/Pages/SelectionPage/selection.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/SignInPage/SignInPage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/SignInPage/signin.scss
  frontend/BudgetingBuddy-frontend/src/Pages/SignInPage/signin.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/WelcomePage/WelcomePage.test.tsx
  frontend/BudgetingBuddy-frontend/src/Pages/WelcomePage/welcome.scss
  frontend/BudgetingBuddy-frontend/src/Pages/WelcomePage/welcome.tsx
  frontend/BudgetingBuddy-frontend/src/assets/frequencyArr.ts
  frontend/BudgetingBuddy-frontend/src/hooks/UseUserInfo.tsx
  frontend/BudgetingBuddy-frontend/src/hooks/UseUserMoneyInfo.tsx
  frontend/BudgetingBuddy-frontend/src/hooks/useGenericApiCall.tsx
  frontend/BudgetingBuddy-frontend/src/index.css
  frontend/BudgetingBuddy-frontend/src/main.tsx
  frontend/BudgetingBuddy-frontend/src/store/UserInformationStore.tsx
  frontend/BudgetingBuddy-frontend/src/store/UserMoneyInfoStore.tsx
  frontend/BudgetingBuddy-frontend/src/types/UserInfoContextTypes.ts
  frontend/BudgetingBuddy-frontend/src/types/UserMoneyInfoContextTypes.ts
  frontend/BudgetingBuddy-frontend/src/utils/sessionStorage.test.ts
  frontend/BudgetingBuddy-frontend/vite.config.ts
  frontend/BudgetingBuddy-frontend/vitest.config.js
Labels: enhancement

#69 Update REQUIREMENTS.md
  REQUIREMENTS.md
Labels: documentation

#71 Feature(#22): Custom Saving Implementation
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/controller/BudgetingController.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/ErrorCode.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/GlobalExceptionHandler.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/BudgetingUserRequest.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingCustomSavingResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingCustomSavingAmount.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/FieldValidation.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingCustomSavingAmountTest.java
  backend/Hoppscotch/backend-testing.json
Labels: enhancement

#73 Revert PR as it broke the app
  frontend/BudgetingBuddy-frontend/src/Pages/SignInPage/signin.tsx
Labels: bug

#78 dashboard styling
  frontend/BudgetingBuddy-frontend/src/Pages/DashboardPage/dashboard.scss
  frontend/BudgetingBuddy-frontend/src/Pages/DashboardPage/dashboard.tsx
  frontend/BudgetingBuddy-frontend/src/index.css
Labels: enhancement

#83 Feature(#21): Pension Calculator Implementation
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/controller/BudgetingController.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/exception/ErrorCode.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/BudgetingUserRequest.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingErrorResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserCarFinanceResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserCustomSavingResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/model/response/BudgetingUserPensionContributionResponse.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingCustomSavingAmount.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/BudgetingPensionContribution.java
  backend/BudgetingCalculator/src/main/java/com/ial/uni/budgeting/calculator/service/FieldValidation.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingCustomSavingAmountTest.java
  backend/BudgetingCalculator/src/test/java/com/ial/uni/budgeting/calculator/service/BudgetingPensionContributionTest.java
  backend/Hoppscotch/backend-testing.json
Labels: enhancement
